### ISSUE TITLE
Settings Tabs are not scrollable

### ISSUE THREAD

**Issue by RichardEpure** [CallumWatkins/crust#39]
![image](https://user-images.githubusercontent.com/43828146/180569193-ebf2a9d9-5d0e-4f71-8046-791334cd2b45.png)

![image](https://user-images.githubusercontent.com/43828146/180569211-1ddc25aa-8021-49be-aa3f-95ec0359b0c8.png)

**Comment by CallumWatkins** [comment]
Depends on #38
